# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laerdon Kim
description: > # this means to ignore newlines until "baseurl:"
  a personal website made by Laerdon Kim
repository: https://github.com/laerdon/laerdon.github.io
baseurl: ""
url: "https://laerdon.github.io"
# Build settings
markdown: kramdown

include:
  - assets

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Laerdon Kim
email: lyk25@cornell.edu

navigation:
  - text: home
    url: "/"
  - text: publications
    url: "/publications"
  - text: CV
    url: "/assets/cv.pdf"
    target: _blank

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: awesome-cryptography
    description: A curated list of cryptography resources and links.
    link: https://github.com/sobolevn/awesome-cryptography
    image: https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg
  - name: ecto_autoslug_field
    description: Automatically creates slugs for your Ecto models.
    link: https://github.com/sobolevn/ecto_autoslug_field
  - name: django-split-settings
    description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
    link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: laerdon
    link: https://github.com/laerdon
  - service: twitter
    username: laerdonkim
    link: https://twitter.com/laerdonkim

# Plugins
plugins:
  - jekyll-seo-tag
